### PR TITLE
Added `--input-file` option

### LINKED ISSUE #27: Supply URLs in file or on standard input
I have a list of URLs I would like to check with fairtally. To do this I need concatenate the list with a space char and pass that long string to the cli. It would be nice if I could directly give it my list of URLs as file or on stdin. Where each URL would be on it own line.

For example a file named `urls.txt`
```csv
https://github.com/fair-software/howfairis
https://gitlab.com/jspaaks/howfairis-livetest
```
I would like to be able to call
```
fairtally --urls urls.txt
# or
fairtally < urls.txt
# or
cat urls.txt | fairtally
```

It would be nice option to have next to #3

### PR DESCRIPTION
**Pull request by sverhoeven**
Fixes #27

For review following commands should all work

```
fairtally https://github.com/fair-software/fairtally
echo 'https://github.com/fair-software/fairtally' > u.txt
cat u.txt | fairtally --input-file -
fairtally --input-file u.txt
```

### CODE REVIEW

**Review by fdiblen — CHANGES_REQUESTED** [review]
Yummy. It is good to see that we now have stdin support. 

Can we we add this to the documentation and provide an example as well?

**Comment by sverhoeven** [comment]
Docs done in #28, which can be merged after this one

**Review by fdiblen — APPROVED** [review]
LVGTM. :heavy_check_mark:  :heavy_check_mark:  :heavy_check_mark:

**Comment by sverhoeven** [comment]
Thnx for reviewing

**Pull request merged**
